name: Twelwe Workflow
on: [push]
  
jobs:
    run_first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Vars—Ü and Secret
            run: |
              echo '${{ vars.STATUS }}'
              echo '${{ secrets.PASSWORD }}'
              